USE [master]
GO

/****** Object:  Database [menu]    Script Date: 2019/12/6 10:03:43 ******/
CREATE DATABASE [menu]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'menu', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\menu.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'menu_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\menu_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [menu].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [menu] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [menu] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [menu] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [menu] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [menu] SET ARITHABORT OFF 
GO

ALTER DATABASE [menu] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [menu] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [menu] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [menu] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [menu] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [menu] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [menu] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [menu] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [menu] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [menu] SET  DISABLE_BROKER 
GO

ALTER DATABASE [menu] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [menu] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [menu] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [menu] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [menu] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [menu] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [menu] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [menu] SET RECOVERY FULL 
GO

ALTER DATABASE [menu] SET  MULTI_USER 
GO

ALTER DATABASE [menu] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [menu] SET DB_CHAINING OFF 
GO

ALTER DATABASE [menu] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [menu] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [menu] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [menu] SET QUERY_STORE = OFF
GO

USE [menu]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [menu] SET  READ_WRITE 
GO

